project:
  type: website
  output-dir: docs

website:
  title: "Einführung in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Allgemeines
        href: Themen/01/01_Allgemeines.qmd
      - text: Deskriptive Statistik
        href: Themen/02/02_DeskriptiveStats.qmd
      - text: Grafische Darstellungen
        href: Themen/03/03_Graph.qmd
 
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true

editor: visual

