project:
  type: website
  output-dir: docs

website:
  title: "Einführung in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Allgemeines
        href: Themen/01/01_Allgemeines.qmd
      - text: Deskriptive Statistik
        href: Themen/02/02_DeskriptiveStats.qmd
      - text: Grafische Darstellungen
        href: Themen/03/03_Graph.qmd
      - text: ANOVA
        href: Themen/04/04_Anova.qmd
      - text: Regression
        href: Themen/05/05_Regression.qmd
      - text: Statistische Modellierung
        href: Themen/06/06_StatMod.qmd
      - text: Experimental Design
        href: Themen/07/07_ExpDesign.qmd
      - text: Two-factorial LM
        href: Themen/08/08_2f_LM.qmd
      - text: Two-factorial GLM
        href: Themen/09/09_2f_GLM.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true

editor: visual

execute: 
  freeze: auto