{
  "hash": "ee80027a9149ed682beccf3ad876ce8f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Einführung in R Markdown - Penguins\"\ndate: \"2025-11-05\"\noutput:\n  word_document:\n   # toc: true\n   # toc_depth: 3\n   # reference_docx: \"ref.docx\"\n---\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"palmerpenguins\")\n#install.packages(c(\"palmerpenguins\", \"ggplot2\", \"dplyr\", \"knitr\", \"DHARMa\", \"emmeans\", \"multcompView\", \"multcomp\", \"broom\", \"pander\"))\n```\n:::\n\n\n## Pakete laden\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(knitr)\nlibrary(DHARMa)\nlibrary(emmeans)\nlibrary(multcompView)\nlibrary(multcomp)\nlibrary(broom)\nlibrary(pander)\n```\n:::\n\n\n## Daten laden\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(penguins)\ndf=penguins\n```\n:::\n\n\n## Struktur prüfen & Daten kennenlernen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df)\nsummary(df)\n```\n:::\n\n\nWir haben 344 Beobachtungen.\n\nWir haben 344 Beobachtungen.\n\n-   3 Faktoren\n-   5 kontinuierliche Variablen\n-   3 Arten\n-   3 Inseln\n-   Missing values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(df))\ndf <- df %>%\n  mutate(species = factor(species, levels = c(\"Chinstrap\", \"Gentoo\", \"Adelie\")))\ndf1 = df %>% filter(complete.cases(.))\ndf2 = df %>% filter(complete.cases(body_mass_g))\ndf %>%\n  count(species, island)\n```\n:::\n\n\n### Tabelle Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(species) %>%\n  summarise(\n    n = sum(!is.na(body_mass_g)),\n    mean_body_mass_g = round(mean(body_mass_g, na.rm = TRUE), 1),\n    sd_body_mass_g   = round(sd(body_mass_g, na.rm = TRUE), 1),\n    median_body_mass_g = round(median(body_mass_g, na.rm = TRUE), 1),\n    min_body_mass_g  = min(body_mass_g, na.rm = TRUE),\n    max_body_mass_g  = max(body_mass_g, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  species       n mean_body_mass_g sd_body_mass_g median_body_mass_g\n  <fct>     <int>            <dbl>          <dbl>              <dbl>\n1 Chinstrap    68            3733.           384.               3700\n2 Gentoo      123            5076            504.               5000\n3 Adelie      151            3701.           459.               3700\n# ℹ 2 more variables: min_body_mass_g <int>, max_body_mass_g <int>\n```\n\n\n:::\n:::\n\n\nmit `library(knitr)` und der Funktion `kable()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(species) %>%\n  summarise(\n    n = sum(!is.na(body_mass_g)),\n    mean_body_mass_g = round(mean(body_mass_g, na.rm = TRUE), 1),\n    sd_body_mass_g   = round(sd(body_mass_g, na.rm = TRUE), 1),\n    median_body_mass_g = round(median(body_mass_g, na.rm = TRUE), 1),\n    min_body_mass_g  = min(body_mass_g, na.rm = TRUE),\n    max_body_mass_g  = max(body_mass_g, na.rm = TRUE)\n  ) %>%\n  kable(\n    caption = \"Zusammenfassung der Körpermasse pro Pinguinart (in g)\",\n    col.names = c(\"Art\", \"n\", \"Mittelwert\", \"StdAbw\", \"Median\", \"Min\", \"Max\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Zusammenfassung der Körpermasse pro Pinguinart (in g)\n\n|Art       |   n| Mittelwert| StdAbw| Median|  Min|  Max|\n|:---------|---:|----------:|------:|------:|----:|----:|\n|Chinstrap |  68|     3733.1|  384.3|   3700| 2700| 4800|\n|Gentoo    | 123|     5076.0|  504.1|   5000| 3950| 6300|\n|Adelie    | 151|     3700.7|  458.6|   3700| 2850| 4775|\n\n\n:::\n:::\n\n\n### Abbildungen\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = species, y = body_mass_g, fill = species)) +\n  stat_boxplot(geom =\"errorbar\", width = 0.3)+\n  geom_boxplot(outlier.shape=NA, width=0.5) +\n  geom_jitter(width=0.1, height=0, shape=16, alpha=0.5)+\n  stat_summary(fun = \"mean\", colour = 1, fill=\"grey\", size = 1, shape=21) +\n  scale_y_sqrt()+\n  scale_fill_manual(values = species_colors)+\n  labs(x = \"Art\",\n       y = \"Körpergewicht (g)\") +\n  theme_bw()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Abb. 1: Körpergewicht je Pinguinart](penguins_files/figure-html/unnamed-chunk-9-1.png){width=1500}\n:::\n:::\n\n\n## ANOVA\n\n### Modell formulieren\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod<-lm(sqrt(body_mass_g) ~ species, data=df)\nanova(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: sqrt(body_mass_g)\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nspecies     2 8437.2  4218.6  331.93 < 2.2e-16 ***\nResiduals 339 4308.4    12.7                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sqrt(body_mass_g) ~ species, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.0578 -2.6022 -0.1917  2.5277  8.3836 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    61.0193     0.4323 141.144   <2e-16 ***\nspeciesGentoo  10.1394     0.5387  18.821   <2e-16 ***\nspeciesAdelie  -0.3015     0.5206  -0.579    0.563    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.565 on 339 degrees of freedom\n  (2 Beobachtungen als fehlend gelöscht)\nMultiple R-squared:  0.662,\tAdjusted R-squared:   0.66 \nF-statistic: 331.9 on 2 and 339 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Modellannahmen prüfen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulationOutput <- simulateResiduals(fittedModel = mod, plot = F)\nplot(simulationOutput)\n```\n\n::: {.cell-output-display}\n![](penguins_files/figure-html/unnamed-chunk-11-1.png){width=792}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotResiduals(simulationOutput, form = df2$species)# NAs in df, besser gleich mit df2 rechnen\n```\n\n::: {.cell-output-display}\n![](penguins_files/figure-html/unnamed-chunk-12-1.png){width=384}\n:::\n:::\n\n\n### Modell interpretieren\n\n#### geschätzte Koeffizienten\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod%>%\n  tidy() %>%\n  kable(col.names = c(\"Predictor\", \"Est\", \"SE\", \"t\", \"p-value\"),\n               digits=c(0,2,2,1,4))\n```\n\n::: {.cell-output-display}\n\n\n|Predictor     |   Est|   SE|     t| p-value|\n|:-------------|-----:|----:|-----:|-------:|\n|(Intercept)   | 61.02| 0.43| 141.1|  0.0000|\n|speciesGentoo | 10.14| 0.54|  18.8|  0.0000|\n|speciesAdelie | -0.30| 0.52|  -0.6|  0.5629|\n\n\n:::\n:::\n\n\nDie Modellkoeffizienten beziehen sich auf das wurzel-transformierte Körpergewicht in g. Das R² des Modells beträgt 66.2.\n\n#### PostHoc-Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCIs=cld(emmeans(mod, ~species, type=\"response\"), adjust=\"sidak\", sort = FALSE, Letters=letters)\nCIs$.group # hier sind noch Leerzeichen enthalten, die die Zentrierung der Buchstaben erschwert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \" a \" \"  b\" \" a \"\n```\n\n\n:::\n\n```{.r .cell-code}\nCIs$.group =gsub(\" \", \"\", CIs$.group, fixed = TRUE)# entfernen der Leerzeichen\nCIs$.group # besser\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\" \"b\" \"a\"\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(CIs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClasses 'summary_emm' and 'data.frame':\t3 obs. of  7 variables:\n $ species : Factor w/ 3 levels \"Chinstrap\",\"Gentoo\",..: 1 2 3\n $ response: num  3723 5064 3687\n $ SE      : num  52.8 45.7 35.2\n $ df      : num  339 339 339\n $ lower.CL: num  3598 4954 3603\n $ upper.CL: num  3851 5174 3772\n $ .group  : chr  \"a\" \"b\" \"a\"\n - attr(*, \"estName\")= chr \"response\"\n - attr(*, \"clNames\")= chr [1:2] \"lower.CL\" \"upper.CL\"\n - attr(*, \"pri.vars\")= chr \"species\"\n - attr(*, \"adjust\")= chr \"sidak\"\n - attr(*, \"side\")= num 0\n - attr(*, \"delta\")= num 0\n - attr(*, \"type\")= chr \"response\"\n - attr(*, \"mesg\")= chr [1:7] \"Confidence level used: 0.95\" \"Conf-level adjustment: sidak method for 3 estimates\" \"Intervals are back-transformed from the sqrt scale\" \"Note: contrasts are still on the sqrt scale. Consider using\\n      regrid() if you want contrasts of back-trans\"| __truncated__ ...\n - attr(*, \"linkname\")= chr \"sqrt\"\n```\n\n\n:::\n\n```{.r .cell-code}\nCIs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n species   response   SE  df lower.CL upper.CL .group\n Chinstrap     3723 52.8 339     3598     3851 a     \n Gentoo        5064 45.7 339     4954     5174 b     \n Adelie        3687 35.2 339     3603     3772 a     \n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 3 estimates \nIntervals are back-transformed from the sqrt scale \nNote: contrasts are still on the sqrt scale. Consider using\n      regrid() if you want contrasts of back-transformed estimates. \nP value adjustment: sidak method for 3 tests \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n\n```{.r .cell-code}\nCIp=data.frame(pairs(regrid(emmeans(mod, ~species)), adjust=\"sidak\"))\nCIp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            contrast    estimate       SE  df     t.ratio  p.value\n1 Chinstrap - Gentoo -1340.20744 69.83099 339 -19.1921594 0.000000\n2 Chinstrap - Adelie    36.70404 63.44083 339   0.5785555 0.916703\n3    Gentoo - Adelie  1376.91148 57.74053 339  23.8465335 0.000000\n```\n\n\n:::\n:::\n\n\n#### Abbildung Daten und geschätzte Mittelwerte und Konfidenzintervall\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = species, y = body_mass_g, fill = species)) +\n  stat_boxplot(geom =\"errorbar\", width = 0.3)+\n  geom_boxplot(outlier.shape=NA, width=0.5) +\n  geom_jitter(width=0.1, height=0, shape=16, alpha=0.5)+\n  geom_errorbar(data=CIs, aes(y=response, ymin=lower.CL, ymax=upper.CL), \n                width=0.1, col=\"grey50\", position = position_nudge(x = 0.4))+\n  geom_point(data=CIs, aes(y=response), \n             shape=16,  size=2, col=\"grey50\", \n             position = position_nudge(x = 0.4))+\n    geom_text(data=CIs, aes(y = 7000, label =.group))+\n  scale_y_sqrt()+\n  scale_fill_manual(values = species_colors)+\n  labs(x = \"Art\",\n       y = \"Körpergewicht (g)\") +\n  theme_bw()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\nRemoved 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Abb. 1: Körpergewicht je Pinguinart](penguins_files/figure-html/unnamed-chunk-15-1.png){width=1800}\n:::\n:::\n\n\nDie geschätzten mittleren Körpermassen (mit 95%-Konfidenzintervallen) sind:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(CIs[,c(1,2,5,6)], caption = \"Geschätztes mittlere Körpergewicht pro Art (g) .\",\n      col.names = c(\"Art\", \"geschätzter Mittelwert\", \"Untere 95%-Konfidenzgrenze\", \"Obere 95%-Konfidenzgrenze\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Geschätztes mittlere Körpergewicht pro Art (g) .\n\n|Art       | geschätzter Mittelwert| Untere 95%-Konfidenzgrenze| Obere 95%-Konfidenzgrenze|\n|:---------|----------------------:|--------------------------:|-------------------------:|\n|Chinstrap |               3723.358|                   3597.833|                  3851.036|\n|Gentoo    |               5063.565|                   4954.386|                  5173.935|\n|Adelie    |               3686.654|                   3602.600|                  3771.677|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nOder wir schreiben im Text:\n\nWir sehen, dass die Gentoo-Pinguine mit einem durchschnittlichen Körpergewicht von etwa 5064 g signifikant schwerer sind als Adelie (p \\< 0.0001) und Chinstrap (p \\< 0.0001) Pinguine, welche ein durchschnittliches Körpergewicht von rund 3687 g und 3723 g aufweisen. Adelie und Chinstrap unterscheiden sich nicht signifikant (p = 0.92).\n\nDank an “Artwork by @allison_horst”.\n\n![](penguins.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncitation(\"palmerpenguins\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTo cite palmerpenguins in publications use:\n\n  Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer\n  Archipelago (Antarctica) penguin data. R package version 0.1.0.\n  https://allisonhorst.github.io/palmerpenguins/. doi:\n  10.5281/zenodo.3960218.\n\nEin BibTeX-Eintrag für LaTeX-Benutzer ist\n\n  @Manual{,\n    title = {palmerpenguins: Palmer Archipelago (Antarctica) penguin data},\n    author = {Allison Marie Horst and Alison Presmanes Hill and Kristen B Gorman},\n    year = {2020},\n    note = {R package version 0.1.0},\n    doi = {10.5281/zenodo.3960218},\n    url = {https://allisonhorst.github.io/palmerpenguins/},\n  }\n```\n\n\n:::\n:::\n\n\n**Abschließende sessionInfo**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.1 (2025-06-13 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19044)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   \n[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   \n[5] LC_TIME=German_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] pander_0.6.6         broom_1.0.10         multcomp_1.4-29     \n [4] TH.data_1.1-3        MASS_7.3-65          survival_3.8-3      \n [7] mvtnorm_1.3-3        multcompView_0.1-10  emmeans_2.0.0       \n[10] DHARMa_0.4.7         knitr_1.50           dplyr_1.1.4         \n[13] ggplot2_4.0.0        palmerpenguins_0.1.1\n\nloaded via a namespace (and not attached):\n [1] utf8_1.2.6         tidyr_1.3.1        sandwich_3.1-1     generics_0.1.4    \n [5] lattice_0.22-7     lme4_1.1-37        digest_0.6.37      magrittr_2.0.3    \n [9] evaluate_1.0.5     grid_4.5.1         estimability_1.5.1 RColorBrewer_1.1-3\n[13] fastmap_1.2.0      jsonlite_2.0.0     Matrix_1.7-3       backports_1.5.0   \n[17] purrr_1.1.0        scales_1.4.0       codetools_0.2-20   reformulas_0.4.1  \n[21] Rdpack_2.6.4       cli_3.6.5          rlang_1.1.6        rbibutils_2.3     \n[25] splines_4.5.1      withr_3.0.2        yaml_2.3.10        tools_4.5.1       \n[29] nloptr_2.2.1       coda_0.19-4.1      minqa_1.2.8        gap.datasets_0.0.6\n[33] boot_1.3-32        vctrs_0.6.5        R6_2.6.1           zoo_1.8-14        \n[37] lifecycle_1.0.4    htmlwidgets_1.6.4  pkgconfig_2.0.3    pillar_1.11.0     \n[41] gtable_0.3.6       glue_1.8.0         Rcpp_1.1.0         xfun_0.52         \n[45] tibble_3.3.0       tidyselect_1.2.1   rstudioapi_0.17.1  xtable_1.8-4      \n[49] farver_2.1.2       htmltools_0.5.8.1  nlme_3.1-168       labeling_0.4.3    \n[53] rmarkdown_2.29     compiler_4.5.1     gap_1.6            S7_0.2.0          \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "penguins_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}