<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ANOVA – Einführung in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Einführung in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/01/01_Allgemeines.html"> 
<span class="menu-text">Allgemeines</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/02/02_DeskriptiveStats.html"> 
<span class="menu-text">Deskriptive Statistik</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/03/03_Graph.html"> 
<span class="menu-text">Grafische Darstellungen</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../Themen/04/04_Anova.html" aria-current="page"> 
<span class="menu-text">ANOVA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/05/05_Regression.html"> 
<span class="menu-text">Regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/06/06_StatMod.html"> 
<span class="menu-text">Statistische Modellierung</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/07/07_ExpDesign.html"> 
<span class="menu-text">Experimental Design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/08/08_2f_LM.html"> 
<span class="menu-text">Two-factorial LM</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Themen/09/09_2f_GLM.html"> 
<span class="menu-text">Two-factorial GLM</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#unterscheiden-sich-die-gruppen" id="toc-unterscheiden-sich-die-gruppen" class="nav-link active" data-scroll-target="#unterscheiden-sich-die-gruppen">Unterscheiden sich die Gruppen?</a></li>
  <li><a href="#beispieldaten-anova-in-anlehnung-an-carsten-dormann-parametrische-statistik-s.-191ff" id="toc-beispieldaten-anova-in-anlehnung-an-carsten-dormann-parametrische-statistik-s.-191ff" class="nav-link" data-scroll-target="#beispieldaten-anova-in-anlehnung-an-carsten-dormann-parametrische-statistik-s.-191ff">Beispieldaten ANOVA in Anlehnung an Carsten Dormann “Parametrische Statistik” S. 191ff</a></li>
  <li><a href="#beispiel-anova-proteingehalt" id="toc-beispiel-anova-proteingehalt" class="nav-link" data-scroll-target="#beispiel-anova-proteingehalt">Beispiel ANOVA Proteingehalt</a></li>
  <li><a href="#daten-einlesen-kennenlernen-und-plotten" id="toc-daten-einlesen-kennenlernen-und-plotten" class="nav-link" data-scroll-target="#daten-einlesen-kennenlernen-und-plotten">Daten einlesen, kennenlernen und plotten</a>
  <ul class="collapse">
  <li><a href="#struktur-der-eingelesenen-daten-überprüfen" id="toc-struktur-der-eingelesenen-daten-überprüfen" class="nav-link" data-scroll-target="#struktur-der-eingelesenen-daten-überprüfen">Struktur der eingelesenen Daten überprüfen</a></li>
  <li><a href="#daten-plotten-ausreißer-eingabefehler-varianzhomogenität-visuell-überprüfen" id="toc-daten-plotten-ausreißer-eingabefehler-varianzhomogenität-visuell-überprüfen" class="nav-link" data-scroll-target="#daten-plotten-ausreißer-eingabefehler-varianzhomogenität-visuell-überprüfen">Daten plotten (Ausreißer, Eingabefehler, Varianzhomogenität visuell überprüfen)</a></li>
  </ul></li>
  <li><a href="#modell-formulieren" id="toc-modell-formulieren" class="nav-link" data-scroll-target="#modell-formulieren">Modell formulieren</a></li>
  <li><a href="#modellinterpretation" id="toc-modellinterpretation" class="nav-link" data-scroll-target="#modellinterpretation">Modellinterpretation</a>
  <ul class="collapse">
  <li><a href="#alternative-funktion-aov" id="toc-alternative-funktion-aov" class="nav-link" data-scroll-target="#alternative-funktion-aov">alternative Funktion aov</a></li>
  </ul></li>
  <li><a href="#modelldiagnostik" id="toc-modelldiagnostik" class="nav-link" data-scroll-target="#modelldiagnostik">Modelldiagnostik</a></li>
  <li><a href="#post-hoc-test" id="toc-post-hoc-test" class="nav-link" data-scroll-target="#post-hoc-test">Post-hoc Test</a>
  <ul class="collapse">
  <li><a href="#bespiel-für-multiples-testen-ohne-und-mit-adjustierung-des-p-wertes" id="toc-bespiel-für-multiples-testen-ohne-und-mit-adjustierung-des-p-wertes" class="nav-link" data-scroll-target="#bespiel-für-multiples-testen-ohne-und-mit-adjustierung-des-p-wertes">Bespiel für multiples Testen ohne und mit Adjustierung des p-Wertes</a></li>
  <li><a href="#post-hoc-test-package-emmeans" id="toc-post-hoc-test-package-emmeans" class="nav-link" data-scroll-target="#post-hoc-test-package-emmeans">Post-hoc Test: package <code>emmeans</code></a></li>
  </ul></li>
  <li><a href="#präsentation-der-ergebnisse" id="toc-präsentation-der-ergebnisse" class="nav-link" data-scroll-target="#präsentation-der-ergebnisse">Präsentation der Ergebnisse</a>
  <ul class="collapse">
  <li><a href="#add-on-faktorlevels-in-grafik-umsortieren" id="toc-add-on-faktorlevels-in-grafik-umsortieren" class="nav-link" data-scroll-target="#add-on-faktorlevels-in-grafik-umsortieren">add on: Faktorlevels in Grafik umsortieren</a></li>
  </ul></li>
  <li><a href="#übung-4" id="toc-übung-4" class="nav-link" data-scroll-target="#übung-4">Übung 4</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ANOVA</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="unterscheiden-sich-die-gruppen" class="level3">
<h3 class="anchored" data-anchor-id="unterscheiden-sich-die-gruppen">Unterscheiden sich die Gruppen?</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Experiment</th>
<th style="text-align: left;">Behandlung</th>
<th style="text-align: right;">MW</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Exp 1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exp 1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Exp 2</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exp 2</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Exp 3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5.1</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exp 3</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">1000</td>
</tr>
</tbody>
</table>
</section>
<section id="beispieldaten-anova-in-anlehnung-an-carsten-dormann-parametrische-statistik-s.-191ff" class="level3">
<h3 class="anchored" data-anchor-id="beispieldaten-anova-in-anlehnung-an-carsten-dormann-parametrische-statistik-s.-191ff">Beispieldaten ANOVA in Anlehnung an Carsten Dormann “Parametrische Statistik” S. 191ff</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
<ol type="A">
<li>Gesamtvarianz der Daten = Abweichungsquadrate zum Gesamtmittelwert = SS Total</li>
<li>Abweichungsquadrate der Gruppen zum Gesamtmittelwert = SS Effekt</li>
<li>Abweichungsquadrate zum Mittelwert der beiden Gruppen = SS Residuen</li>
</ol>
<p>SS<sub>Total</sub> = SS<sub>Effekt</sub> + SS<sub>Residuen</sub><br>
F-Wert = (SS<sub>Effekt</sub>/df<sub>Effekt</sub>)/(SS<sub>Residuen</sub>/df<sub>Residuen</sub>)</p>
<p>df<sub>Effekt</sub> = k-1, wobei k die Anzahl der Gruppen (Faktorlevels) ist<br>
df<sub>Residuen</sub> = n-k, wobei n der Stichprobenumfang ist</p>
<p>F-Wert = MS<sub>Effekt</sub>/MS<sub>Residuen</sub></p>
<p>aus dem F-Wert und den <code>degrees of freedom</code> resultiert dann der p-Wert</p>
<p>R² = SS<sub>Effekt</sub>/SS<sub>Total</sub> * 100</p>
<p>entsprechend können <em>signifikante Unterschiede</em> verschiedene Ursachen haben:</p>
<ul>
<li>große Mittelwertsdifferenzen zwischen den Gruppen (hohe SS<sub>Effekt</sub>)</li>
<li>geringe Variabilität innerhalb der Gruppen (niedrige SS<sub>Residuen</sub>)</li>
<li>hoher Stichprobenumfang bzw. Anzahl Wiederholungen je Gruppe (erhöht df<sub>Residuen</sub> und senkt damit MS<sub>Residuen</sub>)</li>
</ul>
<p>Varianzanalyse (<em>Analysis of Variance</em>)</p>
<ul>
<li><code>mod&lt;-aov(Abhängige ~ Erklärungsvariable, data=md)</code></li>
<li>Abhängige ist kontinuierlich</li>
<li>Erklärungsvariable ist ein Faktor</li>
</ul>
<p>Voraussetzungen:</p>
<ul>
<li>zufällige Stichprobennahme (unabhängige Fehler)</li>
<li>Varianzhomogenität/Homoskedastizität</li>
<li>annähernde Normalverteilung der Fehler (Residuen), und <strong>nicht</strong> der Abhängigen!</li>
</ul>
</section>
<section id="beispiel-anova-proteingehalt" class="level2">
<h2 class="anchored" data-anchor-id="beispiel-anova-proteingehalt">Beispiel ANOVA Proteingehalt</h2>
<p>Die Proteingehalte von jeweils 8 zufällig ausgewählten Weizenproben der 4 Qualitätsklassen E, A, B und C wurden ermittelt. Unterscheiden sich die Qualitätsklassen im Proteingehalt?</p>
</section>
<section id="daten-einlesen-kennenlernen-und-plotten" class="level2">
<h2 class="anchored" data-anchor-id="daten-einlesen-kennenlernen-und-plotten">Daten einlesen, kennenlernen und plotten</h2>
<p><a href="https://github.com/DoreenGabriel/Kurs/blob/main/Themen/04/Protein.xlsx" target="_blank">Protein.xlsx</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>md<span class="ot">&lt;-</span><span class="fu">read.xlsx</span>(<span class="st">"Protein.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="struktur-der-eingelesenen-daten-überprüfen" class="level3">
<h3 class="anchored" data-anchor-id="struktur-der-eingelesenen-daten-überprüfen">Struktur der eingelesenen Daten überprüfen</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(md)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   32 obs. of  3 variables:
 $ ID   : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Quali: chr  "E" "E" "E" "E" ...
 $ Prot : num  15.4 15.6 14.3 13.8 15.4 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(md<span class="sc">$</span>Quali)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "E" "A" "B" "C"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>md<span class="sc">$</span>Quali<span class="ot">=</span><span class="fu">as.factor</span>(md<span class="sc">$</span>Quali)<span class="co"># Erklärungsvariable muss als Faktor deklariert sein</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(md<span class="sc">$</span>Quali)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "A" "B" "C" "E"</code></pre>
</div>
</div>
</section>
<section id="daten-plotten-ausreißer-eingabefehler-varianzhomogenität-visuell-überprüfen" class="level3">
<h3 class="anchored" data-anchor-id="daten-plotten-ausreißer-eingabefehler-varianzhomogenität-visuell-überprüfen">Daten plotten (Ausreißer, Eingabefehler, Varianzhomogenität visuell überprüfen)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(md, <span class="fu">aes</span>(<span class="at">x=</span>Quali, <span class="at">y=</span>Prot)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">geom =</span> <span class="st">"point"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modell-formulieren" class="level2">
<h2 class="anchored" data-anchor-id="modell-formulieren">Modell formulieren</h2>
<p>Wichtig ist, dass die Abhängige kontinuierlich und die Erklärungsvariable ein Faktor ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Prot <span class="sc">~</span> Quali, <span class="at">data=</span>md) <span class="co"># Prot ist die Abhängige, Quali die Erklärungsvariable</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Prot
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
Quali      3 35.666 11.8888  5.0814 0.006198 **
Residuals 28 65.511  2.3397                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><code>Quali</code> hat einen signifikanten Effekt auf den Proteingehalt.</p>
</section>
<section id="modellinterpretation" class="level2">
<h2 class="anchored" data-anchor-id="modellinterpretation">Modellinterpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prot ~ Quali, data = md)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1099 -0.9705  0.2110  0.9566  2.5819 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13.2728     0.5408  24.543   &lt;2e-16 ***
QualiB       -1.0279     0.7648  -1.344    0.190    
QualiC       -1.5594     0.7648  -2.039    0.051 .  
QualiE        1.2036     0.7648   1.574    0.127    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.53 on 28 degrees of freedom
Multiple R-squared:  0.3525,    Adjusted R-squared:  0.2831 
F-statistic: 5.081 on 3 and 28 DF,  p-value: 0.006198</code></pre>
</div>
</div>
<ul>
<li>R² ist 35.3 %. Adjusted R² ist 28.3 %.</li>
<li>Hinter dem Intercept verbirgt sich das erste Level von <code>Quali</code>, i.e.&nbsp;<code>A</code>. <code>A</code> hat demnach einen geschätzten mittleren Proteingehalt von 13.3.</li>
<li>Um den geschätzten mittleren Proteingehalt für <code>B</code> zu ermitteln, müssen wir Intercept + Estimate <code>QualiB</code> rechnen, d.h. 13.3 -1 = 12.2</li>
<li>Um den geschätzten mittleren Proteingehalt für <code>C</code> zu ermitteln, müssen wir Intercept + Estimate <code>QualiC</code> rechnen, d.h. 13.3 -1.6 = 11.7</li>
<li>und für <code>E</code> Intercept + Estimate <code>QualiE</code>: 13.3 + 1.2 = 14.5</li>
</ul>
<section id="alternative-funktion-aov" class="level3">
<h3 class="anchored" data-anchor-id="alternative-funktion-aov">alternative Funktion aov</h3>
<p>… gelangt zu den gleichen Ergebnissen und wird hier lediglich der Vollständigkeit halber erwähnt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod.a<span class="ot">&lt;-</span><span class="fu">aov</span>(Prot <span class="sc">~</span> Quali, <span class="at">data=</span>md) <span class="co"># </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)   
Quali        3  35.67   11.89   5.081 0.0062 **
Residuals   28  65.51    2.34                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(mod.a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aov(formula = Prot ~ Quali, data = md)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1099 -0.9705  0.2110  0.9566  2.5819 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13.2728     0.5408  24.543   &lt;2e-16 ***
QualiB       -1.0279     0.7648  -1.344    0.190    
QualiC       -1.5594     0.7648  -2.039    0.051 .  
QualiE        1.2036     0.7648   1.574    0.127    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.53 on 28 degrees of freedom
Multiple R-squared:  0.3525,    Adjusted R-squared:  0.2831 
F-statistic: 5.081 on 3 and 28 DF,  p-value: 0.006198</code></pre>
</div>
</div>
</section>
</section>
<section id="modelldiagnostik" class="level2">
<h2 class="anchored" data-anchor-id="modelldiagnostik">Modelldiagnostik</h2>
<p>Wir überprüfen die Annahmen der ANOVA visuell auf:</p>
<ul>
<li>annähernde Normalverteilung der Fehler (i.e.&nbsp;Residuen)</li>
<li>Varianzhomogenität</li>
</ul>
<p>Ich nutze hierfür die <code>library(DHARMa)</code>.</p>
<p><a href="https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html" target="_blank">https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>simulationOutput <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(<span class="at">fittedModel =</span> mod, <span class="at">plot =</span> F)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simulationOutput)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Die erste Grafik zeigt einen QQ-Plot der standardisierten <code>Residuen</code>, der uns Informationen über die Normalverteilung der Residuen liefert. Wenn die Punkte ungefähr entlang der Winkelhalbierenden (rote Linie) liegen, deutet dies darauf hin, dass die Residuen approximativ normalverteilt sind. Außerdem werden uns p-Werte für den KS-Test (Kolmogorov-Smirnov-Test auf Normalverteilung), ein Dispersion- und Ausreißertest angezeigt.</p></li>
<li><p>Die zweite Grafik plottet die <code>Residuen</code> gegen die <code>Fitted Values</code>. Wir wollen hier sehen, dass die Streuung um die 0.5 sowohl bei hohen als auch bei niedrigen Werten in etwa gleich ist (<strong>Varianzhomogenität</strong>). Hier scheint ein leichter Trend vorzuliegen (ist aber m.E. noch ok). Der Plot ist auch hilfreich zum Identifizieren von auffälligen Stichproben. Diese werden als rote Sternchen abgebildet (müssen aber noch nicht zwingend als Ausreißer bezeichnet werden).</p></li>
<li><p>Um die Varianzhomogenität zwischen den Gruppen zu prüfen, sollten wir die Residuen gegen die Erklärungsvariablen plotten.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotResiduals</span>(simulationOutput, <span class="at">form =</span> md<span class="sc">$</span>Quali)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Solange alle Tests nicht signifikant sind (und keine roten Linien oder Boxen angezeigt werden), ist alles (mehr oder weniger) gut. ABER es sei angemerkt, dass die Teststärke (Power) der Tests von der Anzahl der Beobachtungen abhängt. Je mehr Beobachtungen wir haben, umso höher ist die Power des Tests. Damit werden häufig signifikante Unterschiede z.B. der Varianzen bei großem Stichprobenumfang beobachtet, obwohl diese praktisch nicht relevant sind. Außerdem werden häufig keine signifikanten Unterschiede bei kleinem Stichprobenumfang beobachtet, obwohl gravierende Unterschiede vorhanden sind.</p>
<p>Die <em>visuelle</em> Modelldiagnostik wird daher häufig als wichtiger angesehen als die p-Wert-basierten Tests auf Normalverteilung und Varianzhomogenität (Cochran, Bartlett und Levenes Test).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tests zur Varianzhomogenität</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(md<span class="sc">$</span>Prot[md<span class="sc">$</span>Quali<span class="sc">==</span><span class="st">"E"</span>], md<span class="sc">$</span>Prot[md<span class="sc">$</span>Quali<span class="sc">==</span><span class="st">"B"</span>] )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  md$Prot[md$Quali == "E"] and md$Prot[md$Quali == "B"]
F = 0.6686, num df = 7, denom df = 7, p-value = 0.6085
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.1338567 3.3396057
sample estimates:
ratio of variances 
         0.6686019 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(Prot <span class="sc">~</span> Quali, <span class="at">data=</span>md)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  Prot by Quali
Bartlett's K-squared = 1.0564, df = 3, p-value = 0.7876</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Prot <span class="sc">~</span> Quali, <span class="at">data=</span>md) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3  0.3349 0.8002
      28               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(outliers)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cochran.test</span>(Prot <span class="sc">~</span> Quali, <span class="at">data=</span>md)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Cochran test for outlying variance

data:  Prot ~ Quali
C = 0.36079, df = 8, k = 4, p-value = 0.6601
alternative hypothesis: Group C has outlying variance
sample estimates:
       A        B        C        E 
1.805174 2.503336 3.376528 1.673735 </code></pre>
</div>
</div>
<p>In unserem Beispiel ist alles ok. Sowohl visuell als auch nach Aussage der Tests.</p>
<section id="hier-ein-beispiel-für-varianzheterogenität-mit-veränderten-daten." class="level4">
<h4 class="anchored" data-anchor-id="hier-ein-beispiel-für-varianzheterogenität-mit-veränderten-daten.">Hier ein Beispiel für Varianzheterogenität mit veränderten Daten.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>md<span class="sc">$</span>Prot2<span class="ot">=</span> md<span class="sc">$</span>Prot</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1309</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>md<span class="sc">$</span>Prot2[md<span class="sc">$</span>Quali<span class="sc">==</span><span class="st">"E"</span>] <span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">8</span>, <span class="fl">14.5</span>, <span class="dv">13</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(md, <span class="fu">aes</span>(<span class="at">x=</span>Quali, <span class="at">y=</span>Prot2)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">geom =</span> <span class="st">"point"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">lm</span>(Prot2 <span class="sc">~</span> Quali, <span class="at">data=</span>md)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>simulationOutput <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(<span class="at">fittedModel =</span> mod2, <span class="at">plot =</span> F)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simulationOutput)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotResiduals</span>(simulationOutput, <span class="at">form =</span> md<span class="sc">$</span>Quali)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die Residuen weisen eine größere Streuung mit größer werdenden <code>fitted values</code> auf bzw. unterscheiden sich die Varianzen der Gruppen. Um dem entgegenzuwirken, könnten wir entweder die Analyse mit transformierten Daten vornehmen oder <em>besser</em> einen Funktion anwenden, die die unterschiedliche Varianz in den Gruppen berücksichtigt. Letzteres ist mit den Funktionen <code>glmmTMB()</code> und <code>lme</code> möglich.</p>
</section>
</section>
<section id="post-hoc-test" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-test">Post-hoc Test</h2>
<p>Die ANOVA hat einen signifikanten Effekt von <code>Quali</code> auf <code>Prot</code> gezeigt. Allerdings wissen wir nicht, welche Weizenqualitätsklassen sich voneinander unterscheiden. Bei Faktoren mit mehr als zwei Ausprägungen wird daher ein Post-hoc Test durchgeführt. Dieser korrigiert die Irrtumswahrscheinlichkeit um die Anzahl der Vergleiche, da bei beispielsweise 100 Ausprägungen schon rein zufällig fünf signifikante Unterschiede auftreten können.</p>
<section id="bespiel-für-multiples-testen-ohne-und-mit-adjustierung-des-p-wertes" class="level3">
<h3 class="anchored" data-anchor-id="bespiel-für-multiples-testen-ohne-und-mit-adjustierung-des-p-wertes">Bespiel für multiples Testen ohne und mit Adjustierung des p-Wertes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(md<span class="sc">$</span>Prot, md<span class="sc">$</span>Quali, <span class="at">p.adj =</span> <span class="st">"none"</span>) <span class="co"># p-Werte werden nicht korrigiert, nicht gut! </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  md$Prot and md$Quali 

  A      B      C     
B 0.1897 -      -     
C 0.0510 0.4928 -     
E 0.1268 0.0069 0.0012

P value adjustment method: none </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bonferroni-Korrektur (Bonferroni multipliziert p mit der Anzahl Tests, sehr konservativ)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(md<span class="sc">$</span>Prot, md<span class="sc">$</span>Quali, <span class="at">p.adj =</span> <span class="st">"bonferroni"</span>) <span class="co"># besser</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  md$Prot and md$Quali 

  A     B     C    
B 1.000 -     -    
C 0.306 1.000 -    
E 0.761 0.041 0.007

P value adjustment method: bonferroni </code></pre>
</div>
</div>
</section>
<section id="post-hoc-test-package-emmeans" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-test-package-emmeans">Post-hoc Test: package <code>emmeans</code></h3>
<p>Die <code>library(emmeans)</code> mit der Funktion <code>emmeans()</code> bietet eine Vielzahl an Möglichkeiten um einen Post-hoc Test am gefitteten Modell (hier die ANOVA) durchzuführen. Mit dem Argument <code>method="pairwise"</code> kann man alle Behandlungen miteinander per Tukey-Test vergleichen, i.e.&nbsp;paarweise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali), <span class="at">method=</span><span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate    SE df t.ratio p.value
 A - B       1.028 0.765 28   1.344  0.5437
 A - C       1.559 0.765 28   2.039  0.1982
 A - E      -1.204 0.765 28  -1.574  0.4093
 B - C       0.532 0.765 28   0.695  0.8981
 B - E      -2.231 0.765 28  -2.918  0.0328
 C - E      -2.763 0.765 28  -3.613  0.0061

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<p>Mit <code>method="trt.vs.ctrl"</code> wird ein Dunnett-Test durchgeführt, der alle Behandlungen gegen <strong>eine</strong> Kontrolle testet. Die p-Werte werden automatisch um die Anzahl der Tests korrigiert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali), <span class="at">method=</span><span class="st">"trt.vs.ctrl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate    SE df t.ratio p.value
 B - A       -1.03 0.765 28  -1.344  0.4116
 C - A       -1.56 0.765 28  -2.039  0.1295
 E - A        1.20 0.765 28   1.574  0.2937

P value adjustment: dunnettx method for 3 tests </code></pre>
</div>
</div>
<p>Hier wird immer gegen die Qualität A geprüft, weil diese das erste Level der Variable <code>Quali</code> ist.</p>
<p>Mit dem Argument <code>ref</code> kann ich ein anderes Level wählen. Hier die E-Qualität.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali), <span class="at">method=</span><span class="st">"trt.vs.ctrl"</span>, <span class="at">ref=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate    SE df t.ratio p.value
 A - E       -1.20 0.765 28  -1.574  0.2937
 B - E       -2.23 0.765 28  -2.918  0.0190
 C - E       -2.76 0.765 28  -3.613  0.0033

P value adjustment: dunnettx method for 3 tests </code></pre>
</div>
</div>
<p>Alternativ kann ich bereits im <code>data.frame</code> die Faktorenlevels entsprechend meiner Interpretation ändern und damit das Modell anpassen. (siehe dazu Reihenfolge ändern in Kap. Grafik)</p>
<p>Interessant sind auch die Konfidenzintervalle. Wenn Konfidenzintervalle sich nicht überlappen, geht man in der Regel von signifikanten Unterschieden aus. Es kann auch sein, dass Konfidenzintervalle leicht überlappen, und trotzdem signifikante Unterschiede vorliegen. <a href="https://core.ac.uk/download/pdf/82702323.pdf" target="_blank">https://core.ac.uk/download/pdf/82702323.pdf</a> Hier sollte man immer auf die p-Werte des Tests schauen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali)) <span class="co">#Konfidenzintervalle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Quali emmean    SE df lower.CL upper.CL
 A       13.3 0.541 28     12.2     14.4
 B       12.2 0.541 28     11.1     13.4
 C       11.7 0.541 28     10.6     12.8
 E       14.5 0.541 28     13.4     15.6

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Um Gruppenunterschiede leicht verständlich anzugeben bzw. zu visualisieren, kann das <em>compact letter display</em> genutzt werden. Hierfür benötigen wir die <code>library(multcompView)</code> und <code>library(multcomp)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcompView)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali), <span class="at">adjust=</span><span class="st">"sidak"</span>, <span class="at">Letters=</span>letters) <span class="co"># Compact letter display für Gruppenunterschiede </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Quali emmean    SE df lower.CL upper.CL .group
 C       11.7 0.541 28     10.3     13.2  a    
 B       12.2 0.541 28     10.8     13.7  a    
 A       13.3 0.541 28     11.8     14.7  ab   
 E       14.5 0.541 28     13.0     15.9   b   

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 4 estimates 
P value adjustment: sidak method for 6 tests 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Gruppen, die keinen Buchstaben gemeinsam haben, sind im Mittelwert signifikant unterschiedlich. Qualitätsklasse <code>E</code> hat einen signifikant höheren Proteingehalt im Vergleich zu <code>B</code> und <code>C</code>, während <code>E</code> und <code>A</code> sich nicht signifikant unterscheiden.</p>
</section>
</section>
<section id="präsentation-der-ergebnisse" class="level2">
<h2 class="anchored" data-anchor-id="präsentation-der-ergebnisse">Präsentation der Ergebnisse</h2>
<p>So könnte man die Daten und die Ergebnisse des Modells präsentieren. Ich speichere das Konfidenzintervall als Objekt <code>CI</code> und plotte es dann in den jittered Boxplot. Das Einzeichnen der Buchstaben muss nicht sein. Der Vollständigkeit halber soll es hier aber gezeigt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>CIs<span class="ot">=</span><span class="fu">cld</span>(<span class="fu">emmeans</span>(mod, <span class="sc">~</span>Quali), <span class="at">adjust=</span><span class="st">"sidak"</span>, <span class="at">sort =</span> <span class="cn">FALSE</span>, <span class="at">Letters=</span>letters)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="co"># hier sind noch Leerzeichen enthalten, die die Zentrierung der Buchstaben erschwert</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] " ab" " a " " a " "  b"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="ot">=</span><span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">""</span>, CIs<span class="sc">$</span>.group, <span class="at">fixed =</span> <span class="cn">TRUE</span>)<span class="co"># entfernen der Leerzeichen</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="co"># besser</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ab" "a"  "a"  "b" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CIs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'summary_emm' and 'data.frame': 4 obs. of  7 variables:
 $ Quali   : Factor w/ 4 levels "A","B","C","E": 1 2 3 4
 $ emmean  : num  13.3 12.2 11.7 14.5
 $ SE      : num  0.541 0.541 0.541 0.541
 $ df      : num  28 28 28 28
 $ lower.CL: num  11.8 10.8 10.3 13
 $ upper.CL: num  14.7 13.7 13.2 15.9
 $ .group  : chr  "ab" "a" "a" "b"
 - attr(*, "estName")= chr "emmean"
 - attr(*, "clNames")= chr [1:2] "lower.CL" "upper.CL"
 - attr(*, "pri.vars")= chr "Quali"
 - attr(*, "adjust")= chr "sidak"
 - attr(*, "side")= num 0
 - attr(*, "delta")= num 0
 - attr(*, "type")= chr "link"
 - attr(*, "mesg")= chr [1:5] "Confidence level used: 0.95" "Conf-level adjustment: sidak method for 4 estimates" "P value adjustment: sidak method for 6 tests" "significance level used: alpha = 0.05" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(md, <span class="fu">aes</span>(<span class="at">x=</span>Quali, <span class="at">y=</span>Prot)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean), </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">16</span>,  <span class="at">size=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">2</span>, </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean, <span class="at">ymin=</span>lower.CL, <span class="at">ymax=</span>upper.CL), </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">width=</span><span class="fl">0.1</span>, <span class="at">col=</span><span class="dv">2</span>, <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">17</span>, <span class="at">label =</span>.group))<span class="sc">+</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">number_format</span>(<span class="at">accuracy =</span> <span class="fl">0.01</span>, </span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">decimal.mark =</span><span class="st">","</span>))<span class="sc">+</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Proteingehalt %"</span>)<span class="sc">+</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Qualitätsklasse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Im Text sollte man erwähnen, dass</p>
<ul>
<li><code>Quali</code> einen signifikanten Einfluss auf <code>Prot</code> hat. Nutze die Funktion <code>anova(mod)</code> und gibt den p-Wert zusammen mit den <code>degrees of freedom</code> und <code>F-Wert</code> an.</li>
<li>der Post-hoc Test gezeigt hat, dass <code>E</code> mit im Mittel 14.5 % einen signifikant höheren Proteingehalt hatte als <code>B</code> und <code>C</code> mit 12.2 % und 11.7 % , während <code>E</code> und <code>A</code> sich nicht unterscheiden. Die Proteingehalte von <code>A</code>, <code>B</code> und <code>C</code> unterscheiden sich nicht signifikant (p&gt;0.05). Hierzu nutzt du die Funktion <code>contrast(emmeans(mod, c("Quali")), method="pairwise")</code>.</li>
<li>das R² des Modells 35.3 beträgt. <code>summary(mod)$r.sq</code></li>
<li>die Modellannahmen für die ANOVA (Varianzhomogenität und annähernde Normalverteilung der Residuen) visuell mit dem Paket <code>DHARMa</code> überprüft wurden.</li>
</ul>
<section id="add-on-faktorlevels-in-grafik-umsortieren" class="level3">
<h3 class="anchored" data-anchor-id="add-on-faktorlevels-in-grafik-umsortieren">add on: Faktorlevels in Grafik umsortieren</h3>
<p>Schöner wäre es, die Qualitäten in absteigender Reihenfolge darzustellen. E steht für Elite und ist die beste Qualität.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>md <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_relevel</span>(Quali, <span class="st">"E"</span>), <span class="at">y=</span>Prot)) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean), </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">shape=</span><span class="dv">16</span>,  <span class="at">size=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">2</span>, </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean, <span class="at">ymin=</span>lower.CL, <span class="at">ymax=</span>upper.CL), </span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">width=</span><span class="fl">0.1</span>, <span class="at">col=</span><span class="dv">2</span>, <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">20</span>, <span class="at">label =</span>.group))<span class="sc">+</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>oder in aufsteigender Reihenfolge, basierend auf den Messwerten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>Prot<span class="ot">=</span>CIs<span class="sc">$</span>emmean</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>md <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">fct_reorder</span>(Quali, Prot), <span class="at">y=</span>Prot)) <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean), </span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">shape=</span><span class="dv">16</span>,  <span class="at">size=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">2</span>, </span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>emmean, <span class="at">ymin=</span>lower.CL, <span class="at">ymax=</span>upper.CL), </span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">width=</span><span class="fl">0.1</span>, <span class="at">col=</span><span class="dv">2</span>, <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">20</span>, <span class="at">label =</span>.group))<span class="sc">+</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="übung-4" class="level2">
<h2 class="anchored" data-anchor-id="übung-4">Übung 4</h2>
<p>In einem Gefäßversuch wurde die pflanzenliche Biomasse (<code>BM</code>) in den 4 Düngemittelvarianten (<code>DM</code>: Kontrolle, Düngemittel A, B und C) an jeweils 10 Proben gemessen.</p>
<ul>
<li>Importiere bitte die Daten <a href="https://github.com/DoreenGabriel/Kurs/blob/main/Themen/04/Gefaessversuch.xlsx" target="_blank">Gefaessversuch.xlsx</a> in R und mach Dich mit dem Datensatz vertraut.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Daten einlesen und prüfen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>g<span class="ot">&lt;-</span><span class="fu">read.xlsx</span>(<span class="st">"Gefaessversuch.xlsx"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   40 obs. of  3 variables:
 $ ID: num  1 2 3 4 5 6 7 8 9 10 ...
 $ DM: chr  "K" "K" "K" "K" ...
 $ BM: num  118.3 122.4 96.7 86.9 119 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(g, <span class="fu">aes</span>(<span class="at">x=</span>DM, <span class="at">y=</span>BM)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">geom =</span> <span class="st">"point"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>wir können die Kontrolle als erstes Level definieren.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>DM<span class="ot">=</span><span class="fu">fct_relevel</span>(g<span class="sc">$</span>DM, <span class="st">"K"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(g, <span class="fu">aes</span>(<span class="at">x=</span>DM, <span class="at">y=</span>BM)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">geom =</span> <span class="st">"point"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ul>
<li>Unterscheidet sich die Biomasse zwischen den Varianten?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Modell formulieren
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(BM <span class="sc">~</span> DM, <span class="at">data=</span>g)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: BM
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
DM         3 431421  143807  67.744 7.084e-15 ***
Residuals 36  76421    2123                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Ja, aber bevor wir das Modell interpretieren, müssen wir uns unbedingt die Residuen anschauen.</p>
</div>
</div>
</div>
<ul>
<li>Sind die Voraussetzung für eine ANOVA gegeben? Prüfe die Residuen.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Modelldiagnostik
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>simulationOutput <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(<span class="at">fittedModel =</span> mod, <span class="at">plot =</span> F)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simulationOutput)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,
: Anpassung beendet mit Schrittweitenfehler - Ergebnisse sorgfältig prüfen</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotResiduals</span>(simulationOutput, <span class="at">form =</span> g<span class="sc">$</span>DM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nein, das sieht nicht gut aus. Die Varianz wird mit jedem Level etwas größer. Hier könnte man nun die Abhängige Variable transformieren, um die Varianz zu stabilisieren.</p>
<p>Plotten wir die Daten mit einer Wurzel-transformierten Y-Achse:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(g, <span class="fu">aes</span>(<span class="at">x=</span>DM, <span class="at">y=</span>BM)) <span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_sqrt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Das sieht besser aus. Die Boxen der Boxplots weisen eine ähnliche Höhe auf.</p>
<p>Nun können wir entweder</p>
<ul>
<li>eine neue Variable in unseren <code>data.frame</code> definieren, die die wurzel-transformierten Werte enthält, z.B. <code>g$BM.sq=sqrt(g$BM)</code></li>
<li>und mit dieser Variable das Modell fitten <code>mod&lt;-lm(BM.sq ~ DM, data=g)</code></li>
<li>und später die emmeans und CIs zurücktransformieren <code>CIs$emmean.2=CIs$emmean^2</code> (gleiches für die Konfidenzintervalle)</li>
</ul>
<p>oder</p>
<ul>
<li>die Transformation im Modell definieren. Das hat bei der späteren Nutzung von <code>emmeans()</code> den Vorteil, dass die Werte auf die <em>Response Skala</em> automatisch tranformiert werden können.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="fu">sqrt</span>(BM) <span class="sc">~</span> DM, <span class="at">data=</span>g)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: sqrt(BM)
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
DM         3 495.26 165.086  69.415 4.885e-15 ***
Residuals 36  85.62   2.378                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>simulationOutput <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(<span class="at">fittedModel =</span> mod1, <span class="at">plot =</span> F)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simulationOutput)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,
: Anpassung beendet mit Schrittweitenfehler - Ergebnisse sorgfältig prüfen
Warning in newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,
: Anpassung beendet mit Schrittweitenfehler - Ergebnisse sorgfältig prüfen</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotResiduals</span>(simulationOutput, <span class="at">form =</span> g<span class="sc">$</span>DM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Auch wenn wir Warnmeldungen für die obigen Plots erhalten, so ist doch die Annahme der Varianzhomogenität und annähernede Normalverteilung der Residuen erfüllt. Wir können das Modell nun interpretieren.</p>
<section id="modellinterpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="modellinterpretation-1">Modellinterpretation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcompView)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM), <span class="at">adjust =</span> <span class="st">"sidak"</span>, <span class="at">Letters=</span>letters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> DM emmean    SE df lower.CL upper.CL .group
 K     9.8 0.488 36     8.52     11.1  a    
 A    11.4 0.488 36    10.15     12.7  a    
 B    14.1 0.488 36    12.85     15.4   b   
 C    19.1 0.488 36    17.81     20.4    c  

Results are given on the sqrt (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: sidak method for 4 estimates 
Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: sidak method for 6 tests 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Die emmeans sind recht niedrig, was an der Wurzeltransformation liegt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM, <span class="at">type=</span><span class="st">"response"</span>), <span class="at">adjust =</span> <span class="st">"sidak"</span>, <span class="at">Letters=</span>letters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> DM response    SE df lower.CL upper.CL .group
 K      96.1  9.56 36     72.6      123  a    
 A     130.6 11.10 36    103.0      161  a    
 B     199.5 13.80 36    165.0      237   b   
 C     364.3 18.60 36    317.1      415    c  

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 4 estimates 
Intervals are back-transformed from the sqrt scale 
Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: sidak method for 6 tests 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Mit dem Argument <code>type="response"</code> werden die emmeans auf die Originalskala zurücktransformiert. Beachte, dass jetzt die Variable <code>reponse</code> heißt und der Code für die Grafik angepasst werden muss. Die p-Werte der paarweisen Vergleiche können wir über die <code>contrast()</code>-Funktion erhalten. Alternativ kann mit dem Argument <code>method="trt.vs.ctrl"</code> ein Dunnett-Test durchgeführt werden, der die Düngemittel A, B und C gegen die <strong>Kontrolle</strong> testet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM), <span class="at">method=</span><span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 K - A       -1.63 0.69 36  -2.361  0.1032
 K - B       -4.32 0.69 36  -6.270  &lt;.0001
 K - C       -9.29 0.69 36 -13.464  &lt;.0001
 A - B       -2.70 0.69 36  -3.909  0.0021
 A - C       -7.66 0.69 36 -11.103  &lt;.0001
 B - C       -4.96 0.69 36  -7.194  &lt;.0001

Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM), <span class="at">method=</span><span class="st">"trt.vs.ctrl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 A - K        1.63 0.69 36   2.361  0.0633
 B - K        4.32 0.69 36   6.270  &lt;.0001
 C - K        9.29 0.69 36  13.464  &lt;.0001

Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: dunnettx method for 3 tests </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM), <span class="at">adjust =</span> <span class="st">"sidak"</span>, <span class="at">method=</span><span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 K - A       -1.63 0.69 36  -2.361  0.1343
 K - B       -4.32 0.69 36  -6.270  &lt;.0001
 K - C       -9.29 0.69 36 -13.464  &lt;.0001
 A - B       -2.70 0.69 36  -3.909  0.0024
 A - C       -7.66 0.69 36 -11.103  &lt;.0001
 B - C       -4.96 0.69 36  -7.194  &lt;.0001

Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: sidak method for 6 tests </code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM), <span class="at">adjust =</span> <span class="st">"sidak"</span>, <span class="at">method=</span><span class="st">"trt.vs.ctrl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df t.ratio p.value
 A - K        1.63 0.69 36   2.361  0.0696
 B - K        4.32 0.69 36   6.270  &lt;.0001
 C - K        9.29 0.69 36  13.464  &lt;.0001

Note: contrasts are still on the sqrt scale. Consider using
      regrid() if you want contrasts of back-transformed estimates. 
P value adjustment: sidak method for 3 tests </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>CIs<span class="ot">=</span><span class="fu">cld</span>(<span class="fu">emmeans</span>(mod1, <span class="sc">~</span>DM, <span class="at">type =</span> <span class="st">"response"</span> ), <span class="at">adjust =</span> <span class="st">"sidak"</span>, <span class="at">sort =</span> <span class="cn">FALSE</span>, <span class="at">Letters=</span>letters)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="co"># hier sind noch Leerzeichen enthalten, die die Zentrierung der Buchstaben erschwert</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] " a  " " a  " "  b " "   c"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="ot">=</span><span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">""</span>, CIs<span class="sc">$</span>.group, <span class="at">fixed =</span> <span class="cn">TRUE</span>)<span class="co"># entfernen der Leerzeichen</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>CIs<span class="sc">$</span>.group <span class="co"># besser</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "a" "a" "b" "c"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CIs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'summary_emm' and 'data.frame': 4 obs. of  7 variables:
 $ DM      : Factor w/ 4 levels "K","A","B","C": 1 2 3 4
 $ response: num  96.1 130.6 199.5 364.3
 $ SE      : num  9.56 11.15 13.78 18.62
 $ df      : num  36 36 36 36
 $ lower.CL: num  72.6 103 165 317.1
 $ upper.CL: num  123 161 237 415
 $ .group  : chr  "a" "a" "b" "c"
 - attr(*, "estName")= chr "response"
 - attr(*, "clNames")= chr [1:2] "lower.CL" "upper.CL"
 - attr(*, "pri.vars")= chr "DM"
 - attr(*, "adjust")= chr "sidak"
 - attr(*, "side")= num 0
 - attr(*, "delta")= num 0
 - attr(*, "type")= chr "response"
 - attr(*, "mesg")= chr [1:7] "Confidence level used: 0.95" "Conf-level adjustment: sidak method for 4 estimates" "Intervals are back-transformed from the sqrt scale" "Note: contrasts are still on the sqrt scale. Consider using\n      regrid() if you want contrasts of back-trans"| __truncated__ ...
 - attr(*, "linkname")= chr "sqrt"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(g, <span class="fu">aes</span>(<span class="at">x=</span>DM, <span class="at">y=</span>BM)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom =</span><span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.25</span>, <span class="at">height=</span><span class="dv">0</span>, <span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>response), </span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">16</span>,  <span class="at">size=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">2</span>, </span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y=</span>response, <span class="at">ymin=</span>lower.CL, <span class="at">ymax=</span>upper.CL), </span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">width=</span><span class="fl">0.1</span>, <span class="at">col=</span><span class="dv">2</span>, <span class="at">position =</span> <span class="fu">position_nudge</span>(<span class="at">x =</span> <span class="fl">0.4</span>))<span class="sc">+</span></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data=</span>CIs, <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">550</span>, <span class="at">label =</span>.group))<span class="sc">+</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_sqrt</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">300</span>,<span class="dv">400</span>,<span class="dv">500</span>))<span class="sc">+</span></span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Biomasse (g)"</span>)<span class="sc">+</span></span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Düngemittel"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Anova_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
<p>Ende Übung 4</p>

<p>:::</p>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>